// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBaVkNNWEuthP2jJPPeHmxufj8K8s-NRI',
    appId: '1:29494912465:web:bc11f9ed1304c803d42cf0',
    messagingSenderId: '29494912465',
    projectId: 'rfid-274e7',
    authDomain: 'rfid-274e7.firebaseapp.com',
    storageBucket: 'rfid-274e7.firebasestorage.app',
    measurementId: 'G-01K7FBHR4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAebHAI9dQ3zEwh1-12pbYVXS4CtVSTlpE',
    appId: '1:29494912465:android:87bf689478eb3096d42cf0',
    messagingSenderId: '29494912465',
    projectId: 'rfid-274e7',
    storageBucket: 'rfid-274e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOQjrqJ1iRTaoDA8ptXXo2yvUfjLVOQG8',
    appId: '1:29494912465:ios:8e6f145d0ae59b90d42cf0',
    messagingSenderId: '29494912465',
    projectId: 'rfid-274e7',
    storageBucket: 'rfid-274e7.firebasestorage.app',
    iosBundleId: 'com.example.myRfid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOQjrqJ1iRTaoDA8ptXXo2yvUfjLVOQG8',
    appId: '1:29494912465:ios:8e6f145d0ae59b90d42cf0',
    messagingSenderId: '29494912465',
    projectId: 'rfid-274e7',
    storageBucket: 'rfid-274e7.firebasestorage.app',
    iosBundleId: 'com.example.myRfid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBaVkNNWEuthP2jJPPeHmxufj8K8s-NRI',
    appId: '1:29494912465:web:6d0e801555a44fbbd42cf0',
    messagingSenderId: '29494912465',
    projectId: 'rfid-274e7',
    authDomain: 'rfid-274e7.firebaseapp.com',
    storageBucket: 'rfid-274e7.firebasestorage.app',
    measurementId: 'G-BMWNW3B41W',
  );
}
